### ISSUE TITLE
Can't add dependency

### ISSUE THREAD

**Issue by JRQuimora** [Abdulazeezvp/windows_system_info#1]
while doing `$ flutter pub add windows_system_info`  command, it throws an error "Because system_monitor depends on windows_system_info any which doesn't exist (could not find package windows_system_info at https://pub.dartlang.org), version solving failed. pub finished with exit code 65"

**Comment by Abdulazeezvp** [comment]
I will try to publish it in pub.dev ASAP, but for now, please add it manually using the GitHub master branch as follows:

https://stackoverflow.com/a/54023220/12973247

**Comment by Abdulazeezvp** [comment]
package has been published, and I hope that it will be available shortly.
