### ISSUE TITLE
Question - can I initialize faster?

### ISSUE THREAD

**Issue by millie-molly** [Abdulazeezvp/windows_system_info#3]
A WindowsSystemInfo.initWindowsInfo(). method takes around 30_60 seconds. ( in release mode either )
can I make it faster?

**Comment by Abdulazeezvp** [comment]
Yes, it is achievable if we initialise simply exactly what we require. If you could offer a hand, we would be grateful to take it.The WMI command itself takes a long time to run.

**Comment by millie-molly** [comment]
I just need "WindowsSystemInfo.system?.model", also "WindowsSystemInfo.system?.uuid" 
but the WMI command takes a long time, how can I get those two faster?

**Comment by Abdulazeezvp** [comment]
I'll make an effort to integrate this in the upcoming version.
Currently, you can reuse the library model without initializing it. However, we advise going deep into the source code so you can reuse the library's helper functions for your use case.

Run this PowerShell command at https://github.com/Abdulazeezvp/windows_system_info/blob/7004e8d75b6eba1feeadeba1881b2ffa64dadeff/lib/src/general_helper.dart#L15

https://github.com/Abdulazeezvp/windows_system_info/blob/7004e8d75b6eba1feeadeba1881b2ffa64dadeff/lib/src/general_helper.dart#L472 Using this function will give you a string with the information you needed.

and pass the string to https://github.com/Abdulazeezvp/windows_system_info/blob/7004e8d75b6eba1feeadeba1881b2ffa64dadeff/lib/src/general_helper.dart#L398  like in this line https://github.com/Abdulazeezvp/windows_system_info/blob/7004e8d75b6eba1feeadeba1881b2ffa64dadeff/lib/src/windows_info_functions.dart#L168
will return a Mapstring,dynamic> and pass this to https://github.com/Abdulazeezvp/windows_system_info/blob/7004e8d75b6eba1feeadeba1881b2ffa64dadeff/lib/models/system_info.dart#L4 The values you need will be returned by this model. Running in isolate mode is also advised.

**Comment by millie-molly** [comment]
bnag!! thanks a lot :) 👍
